name: SPIDER
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9.2
  - r-base=4.1.1
  - pip=22.0.4
  - r-devtools=2.4.3
  - bioconductor-singler
  - bioconductor-celldex
  - bioconductor-singlecellexperiment
  - r-anndata
  - r-reticulate
  - r-seurat=4.3.0
  - pip:
    - scanpy==1.10.1
    - scvi-tools==0.12.1
    - utils==1.0.1
    - anndata==0.8.0
    - torchmetrics==0.7.3
    - matplotlib==3.9.0
    - pandas==1.5.0
    - numpy==1.23.0
    - numba==0.57.0
    - torch==1.11.0
    - scipy==1.8.0
    - scikit-learn==1.0.2
    - requests==2.27.1
    
